### ISSUE TITLE
Use panderas schema.

### ISSUE THREAD

**Issue by aidiss** [dovissssss/exported_lost_pets_from_lithuania#5]
Use panderas schema.
Including renames
Fix dtypes

**Comment by dovissssss** [comment]
Separated panderas schemas into different file with the commit d8ba6f06437c0b2438516d2ce99b2a0ab688162e

Then I applied exported lost pets schema model to read_exported_pets_dataset function, with this commit I also removed dtype section from function 7ba49cdf1ea219faa05a1822b7c563811c6c914a

Also added @pa.check_types for datasets at ea8c8ac322a8731c4965f194d526e954df6d8b6e and 79583a7057068e565d1db853a84d09b3aaaf42ae

**Comment by aidiss** [comment]
Nice description of the commits.
I would still prefer a Pull Request instead.

Overall changes look good. However, in Python class names should always UseThisConvention also known as PascalCase

**Comment by dovissssss** [comment]
Applied PascalCase naming with commit 70d81a5debd276c7c6baa2b29f993f9ea51439ca
